### ISSUE TITLE
Screen capture version of the visit reports is not rendering onscreen items

### ISSUE THREAD

**Issue by cdoran99** [cssat/sprout-issues#67]

**Comment by joemienko** [comment]
The stated issue here is that the visit report check boxes are non distinguishable when using the browser print feature. 

The screen grab below shows the print preview of visit report with "all boxes checked" in the application, but not indication of having been checked in the printed version of the report. 

<img width="622" alt="Screen Shot 2020-02-04 at 8 51 45 AM" src="https://user-images.githubusercontent.com/37134346/73766984-ad025b00-472b-11ea-8fcb-48ce68d983f0.png">

For legal reasons, printing the rendered web page from the browser is required in the context of discovery and disclosure. 

Per Aaron Mason ands others present when this issue was logged, we can either 

1. Have DCYF set [master prefs](https://support.google.com/chrome/a/answer/187948?hl=en) for chrome on managed devices such that the visit reports render in color (note this would have the side effect of rendering all chrome print jobs in color, which is probably not desired), or 

2. Have CSSAT look at design changes which can make checked report boxes distinguishable from unchecked boxes from the browser print dialog.
