### ISSUE TITLE
Visit supervisors cannot properly classify visits missed due to COVID-19

### ISSUE THREAD

**Issue by joemienko** [cssat/sprout-issues#94]

**Comment by joemienko** [comment]
@Deanna1968, @jessicamorris64  - Should we just make this change instead of walking through the full UAT process?

**Comment by sarahyatsko** [comment]
Email from Jamie Chestnutt

![image001](https://user-images.githubusercontent.com/49733235/76882715-4bf49980-6838-11ea-9730-fae84b769130.png)
Hi Deanna and Sarah,
 
With all the issues surrounding COVID-19 can we request that you add to the missed/cancel report dropdown under “cause”. It would be great to have COVID listed as its own option, instead of using illness since this is a specific issue. The providers asked about this during our call with them today. I have included a screen shot so you know which part I am referring to. It doesn’t have to say COVID necessarily, but it would be helpful if it was different than illness.
 
Thanks,
Jamie

**Comment by joemienko** [comment]
@Deanna1968 @jessicamorris64  - Any additional thoughts on whether or not we should do this?

**Comment by joemienko** [comment]
@Deanna1968  - I believe we have decided that we do not want to list COVID-19 specifically. Is this still the case?

**Comment by Deanna1968** [comment]
that is still the case
thanks

**Comment by joemienko** [comment]
Ask is to have a technical "cause" of the missed visit. (per @Deanna1968 )
